partial translation into polish
justgetmydata/jgmd pull request #43
Opened 2021-02-14 09:36 UTC by wojgx

2021-02-14 16:48 UTC, daviddavo commented
Hello, you seem to be using the character `"` to quote, which seems to mess with the file format (JSON), please replace the quotes with `\"`, then we can merge the Pull Request.

Thank you for contributing!

2021-07-27 01:42 UTC, potatto99 requested changes

2021-07-27 01:42 UTC, potatto99 commented on _data/sites.json
> +    "notes_pl": "Wejdź na stronę https://www.amazon.com/gp/help/customer/display i w dół, w poszukiwaniu tematu pomocy, przejdź do sekcji 'Bezpieczeństwo i prywatność' i "Jak mogę zażądać moich danyc
```suggestion
    "notes_pl": "Wejdź na stronę https://www.amazon.com/gp/help/customer/display i w dół, w poszukiwaniu tematu pomocy, przejdź do sekcji \"Bezpieczeństwo i prywatność\" i \"Jak mogę zażądać moich danych?\" Tam kliknij \"Request My Data\", wybierz, czego potrzebujesz i kliknij \"Send Request\". Na Twój adres e-mail powiązany z Amazonem zostanie wysłana wiadomość e-mail z prośbą o potwierdzenie prośby o dane. Wystarczy kliknąć \"Potwierdź\" i poczekać, aż dane będą gotowe do pobrania."

2021-07-27 01:42 UTC, potatto99 commented on _data/sites.json
>      "notes_es": "Ve al formulario indicado en la dirección superior y rellénalo seleccionando la opción 'Solicitar información o una acción relativa a los datos de la cuenta'."
```suggestion
    "notes_es": "Ve al formulario indicado en la dirección superior y rellénalo seleccionando la opción 'Solicitar información o una acción relativa a los datos de la cuenta'.",

2021-07-28 08:28 UTC, merged